spring.application.name=financial_backend
server.port=8080


# POSTGRESQL DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/financialdb
spring.datasource.username=postgres
spring.datasource.password=postgres




# JPA/HIBERNATE
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false


# LOGGING
logging.level.org.springframework=INFO
logging.level.com.luis=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# CORS
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true


# JWT
security.jwt.secret=36bed2513d8b28f100997896e53f0b808fde209ef71711beb61fd793de74dade
security.jwt.expiration=3600000
security.jwt.refresh-expiration=604800000